# Generated by Django 5.0.1 on 2024-11-26 21:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified_communications', '0002_estimate_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
