# Generated by Django 5.0.1 on 2024-11-27 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified_communications', '0003_estimate_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_products', to='unified_communications.estimate')),
            ],
        ),
    ]
