# Generated by Django 5.0.1 on 2024-11-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified_communications', '0004_selectedproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='unique_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
