# Generated by Django 5.0.1 on 2024-12-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified_communications', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='intended_use',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='unique_id',
            field=models.CharField(default='', editable=False, max_length=10, unique=True),
        ),
    ]
