# Generated by Django 5.0.1 on 2024-12-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified_communications', '0007_alter_estimate_intended_use_alter_estimate_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfg_part', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('term_in_months', models.PositiveIntegerField(blank=True, null=True)),
                ('list_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('standard_discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('additional_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gross_margin', models.DecimalField(decimal_places=2, default=25.0, max_digits=5)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('adjusted_gross_margin', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('ext_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ext_total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
