# Generated by Django 5.0.1 on 2024-12-13 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified_communications', '0010_unifiedcommunicationsproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='PricingDetails',
        ),
        migrations.RemoveField(
            model_name='selectedproduct',
            name='estimate',
        ),
        migrations.DeleteModel(
            name='UnifiedCommunicationsProduct',
        ),
        migrations.AddField(
            model_name='salespricing',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_pricings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profile',
        ),
        migrations.DeleteModel(
            name='SelectedProduct',
        ),
    ]
