# Generated by Django 5.0.1 on 2024-12-16 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unified_communications', '0011_delete_pricingdetails_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estimate',
        ),
        migrations.RemoveField(
            model_name='salespricing',
            name='user',
        ),
        migrations.DeleteModel(
            name='WebexCallingFlex',
        ),
        migrations.DeleteModel(
            name='WebexCallingOnPremHybrid',
        ),
        migrations.DeleteModel(
            name='WebexCallingWholesale',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table=None,
        ),
        migrations.DeleteModel(
            name='SalesPricing',
        ),
    ]
