# Generated by Django 5.0.1 on 2024-12-16 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified_communications', '0012_delete_estimate_remove_salespricing_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebexCallingFlex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('list_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'webex_calling_flex',
            },
        ),
        migrations.CreateModel(
            name='WebexCallingOnPremHybrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('list_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'webex_calling_onprem_hybrid',
            },
        ),
        migrations.CreateModel(
            name='WebexCallingWholesale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('list_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'webex_calling_wholesale',
            },
        ),
        migrations.CreateModel(
            name='SalesPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfg_part_number', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('qty', models.IntegerField()),
                ('term_in_months', models.IntegerField(blank=True, null=True)),
                ('list_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('connx_std_discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('deal_specific_discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('connx_std_gross_margin', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('adjusted_gross_margin_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ext_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ext_total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_pricings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_pricing',
            },
        ),
    ]
