# Generated by Django 5.0.1 on 2024-12-16 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unified_communications', '0013_webexcallingflex_webexcallingonpremhybrid_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profiles',
        ),
    ]
