# Generated by Django 5.0.1 on 2024-12-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified_communications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='switches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('list_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'switches',
            },
        ),
    ]
