# Generated by Django 5.0.1 on 2024-12-16 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unified_communications', '0004_estimate'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='salespricing',
            table='ucaas.sales_pricing',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='public.user_profiles',
        ),
        migrations.AlterModelTable(
            name='webexcallingflex',
            table='ucaas.webex_calling_flex',
        ),
        migrations.AlterModelTable(
            name='webexcallingonpremhybrid',
            table='ucaas.webex_calling_onprem_hybrid',
        ),
        migrations.AlterModelTable(
            name='webexcallingwholesale',
            table='ucaas.webex_calling_wholesale',
        ),
    ]
