# Generated by Django 5.0.1 on 2024-12-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified_communications', '0005_alter_salespricing_table_alter_userprofile_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespricing',
            name='connx_std_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='salespricing',
            name='deal_specific_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
