# Generated by Django 5.0.1 on 2025-01-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified_communications', '0007_professionalservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalservice',
            name='size',
        ),
        migrations.AddField(
            model_name='professionalservice',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='professionalservice',
            name='size_range_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionalservice',
            name='size_range_start',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
