# Generated by Django 5.0.1 on 2025-01-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified_communications', '0008_remove_professionalservice_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professionalservice',
            old_name='cost',
            new_name='inital_cost',
        ),
        migrations.AddField(
            model_name='professionalservice',
            name='calculated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
