# Generated by Django 5.0.1 on 2025-01-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified_communications', '0009_rename_cost_professionalservice_inital_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalservice',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
