# Generated by Django 5.0.1 on 2025-02-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unified_communications", "0010_professionalservice_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="salespricing",
            name="type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user_level",
            field=models.CharField(
                choices=[("internal", "Internal"), ("external", "External")],
                default="internal",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="SKU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=255)),
                (
                    "subcategory",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "product_family",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "product_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "list_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "unique_together": {
                    (
                        "category",
                        "subcategory",
                        "product_family",
                        "product_type",
                        "product_name",
                        "sku",
                    )
                },
            },
        ),
    ]
