# Generated by Django 5.0.1 on 2025-02-21 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "unified_communications",
            "0011_salespricing_type_alter_userprofile_user_level_sku",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="professionalservice",
            old_name="efforts_in_days",
            new_name="effort_in_days",
        ),
        migrations.RenameField(
            model_name="professionalservice",
            old_name="size_range_end",
            new_name="per_batch",
        ),
        migrations.RenameField(
            model_name="professionalservice",
            old_name="size_range_start",
            new_name="updated_quantity",
        ),
        migrations.RemoveField(
            model_name="professionalservice",
            name="calculated_cost",
        ),
    ]
