# Generated by Django 5.0.1 on 2025-06-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified_communications', '0012_rename_efforts_in_days_professionalservice_effort_in_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalservice',
            name='effort_in_days',
        ),
        migrations.RemoveField(
            model_name='professionalservice',
            name='per_batch',
        ),
        migrations.RemoveField(
            model_name='professionalservice',
            name='updated_quantity',
        ),
        migrations.RemoveField(
            model_name='salespricing',
            name='type',
        ),
        migrations.AddField(
            model_name='professionalservice',
            name='calculated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='professionalservice',
            name='efforts_in_days',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='professionalservice',
            name='size_range_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionalservice',
            name='size_range_start',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
