# Generated by Django 5.0.1 on 2025-07-11 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unified_communications', '0015_salespricing_item_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salespricing',
            name='item_type',
        ),
    ]
