# Generated by Django 5.0.1 on 2025-07-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified_communications', '0016_remove_salespricing_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salespricing',
            name='item_type',
            field=models.CharField(default='paper_mache', max_length=255),
        ),
    ]
