# Generated by Django 5.0.1 on 2025-07-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unified_communications', '0017_salespricing_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespricing',
            name='item_type',
            field=models.CharField(default='placeholder', max_length=255),
        ),
    ]
