# Generated by Django 5.0.1 on 2025-07-14 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unified_communications', '0018_alter_salespricing_item_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebexAiAgent',
        ),
        migrations.DeleteModel(
            name='WebexContactCenterAddons',
        ),
    ]
